### ISSUE TITLE
ninja build error

### ISSUE THREAD

**Issue by charlesCXK** [mapillary/inplace_abn#112]
Here is my system info:

- PyTorch: 1.0.0
- CUDA: 9.1
- GCC: 5.4.0
- OS: Ubuntu 16.04

How could this happen?
I use the old version InplaceABN successfully with PyTorch 0.4.0, but some errors occur when I want to build the lastest version of InplaceABN.

```
Traceback (most recent call last):
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "network.py", line 10, in <module>
    import resnet101
  File "../../basemodel/resnet101.py", line 14, in <module>
    from LibInplaceABN.modules import InPlaceABNSync, ABN, GlobalAvgPool2d
  File "../../lib/LibInplaceABN/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "../../lib/LibInplaceABN/modules/bn.py", line 10, in <module>
    from .functions import *
  File "../../lib/LibInplaceABN/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': [1/4] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/chen/anaconda3/envs/disabn/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
FAILED: inplace_abn_cpu.o 
c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/chen/anaconda3/envs/disabn/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp: In function ‘std::vector<at::Tensor> backward_cpu(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, bool, float)’:
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp:82:34: error: could not convert ‘z.at::Tensor::type()’ from ‘at::Type’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
   auto dweight = at::empty(z.type(), {0});
                                  ^
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp:83:32: error: could not convert ‘z.at::Tensor::type()’ from ‘at::Type’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
   auto dbias = at::empty(z.type(), {0});
                                ^
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp:89:29: error: could not convert ‘{dx, dweight, dbias}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<at::Tensor>’
   return {dx, dweight, dbias};
                             ^
[2/4] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/chen/anaconda3/envs/disabn/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/chen/anaconda3/envs/disabn/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(99): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(99): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
            argument types are: (int64_t)

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(100): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(100): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
            argument types are: (int64_t)

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(202): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(202): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
            argument types are: (int64_t)

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(203): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(203): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
            argument types are: (int64_t)

8 errors detected in the compilation of "/tmp/tmpxft_00003692_00000000-6_inplace_abn_cuda.cpp1.ii".
[3/4] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/chen/anaconda3/envs/disabn/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn.cpp -o inplace_abn.o
In file included from /home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn.cpp:1:0:
/home/chen/anaconda3/envs/disabn/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
ninja: build stopped: subcommand failed.
```

**Comment by rotabulo** [comment]
@charlesCXK please try upgrading to CUDA 9.2.

**Comment by charlesCXK** [comment]
Thank you for your reply so quickly !
I tried to use CUDA 9.2 just now, and the same error occured.
I rememberd that I had built the newest version of InplaceABN with CUDA 9.0 a couple days ago, so maybe it doesn't matter with the  CUDA version. Is there any other solution possible?

**Comment by rotabulo** [comment]
Are you using pytorch1.0 that comes pre-built with CUDA 9.x with x<=1 ?

**Comment by charlesCXK** [comment]
I am using PyTorch 1.0.0 built from conda (Tsinghua University's channel)
The main difference between conda-pytorch and source code-pytorch is `_GLIBCXX_USE_CXX11_ABI`, but this problem was solved in PyTorch 1.0.0 [here:](https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/2)

In fact, I use PyTorch installed by conda all the time, and I once built the newest version of Inplace ABN successfully as I mentioned above. So I was stuck here.

**Comment by charlesCXK** [comment]
Acyually, I am curious about what caused the error:
`/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu(99): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists`

**Comment by rotabulo** [comment]
@charlesCXK you cannot use the old version of inplaceABN with the new version of PyTorch. You need to switch to the latest release of InplaceABN.

**Comment by charlesCXK** [comment]
-:) I used the latest version of InplaceABN by `git clone https://github.com/mapillary/inplace_abn.git` this month.

**Comment by rotabulo** [comment]
@charlesCXK I am a bit confused here. Your error points e.g. to the following line:
```
/home/chen/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp:83:32: error: could not convert ‘z.at::Tensor::type()’ from ‘at::Type’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
   auto dbias = at::empty(z.type(), {0});
```

but there is no such line in the latest version of `inplace_abn_cpu.cpp`. Indeed, that part was removed after a commit on 28th Nov 2018.

**Comment by charlesCXK** [comment]
@rotabulo 
Oh it was my fault, I am so sorry to bother you.
In my code `network.py`, I import the function `InPlaceABNSync` from the **lastest version** of InplaceABN, but in the backbone ResNet (another code file `resnet.py`), I import the function `InPlaceABNSync` from the **old version** of InplaceABN. `from resnet import ResNet` is used in the file `network.py`, so the above error occured. Thank you for your patient reply! Your work is quite excellent.
