### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [mapillary/inplace_abn#142]
detection/inplace_abn/output', '--world-size', '1', '--rank', '0']
--- Loading model from snapshot
Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 306, in <module>
    main()
  File "test_vistas_single_gpu.py", line 156, in main
    model = model.cuda().eval()
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

**Comment by NarasimmanSaravana1994** [comment]
Is there are argument run without GPU ?
