### ISSUE TITLE
from . import _backend

### ISSUE THREAD

**Issue by zhizhangxian** [mapillary/inplace_abn#147]
Great work， Awesome！
When I install the ABN just follow the readme.md , it successed. 
But when I use the command ``` from inplace_abn import ABN ``` in python , it will return an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangxian03/.jupyter/november/19.nov/inplace_abn/inplace_abn/__init__.py", line 2, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/zhangxian03/.jupyter/november/19.nov/inplace_abn/inplace_abn/abn.py", line 6, in <module>
    from .functions import *
  File "/home/zhangxian03/.jupyter/november/19.nov/inplace_abn/inplace_abn/functions.py", line 5, in <module>
    from . import _backend
```
but when I rename the file "inplace_abn/inplace_abn/_backend.pyi " to "inplace_abn/inplace_abn/_backend.py ", it can work, how do you think about it? Or should I use another way to solve it? Thank!

**Comment by ducksoup** [comment]
@zhizhangxian are you by any chance running your script or your python console from `inplace_abn`'s main folder? In that case python will try to load the `inplace_abn` library from the local copy, which does not contain the compiled native library, instead of the one you installed following the instructions in `README`. This is the reason why our scripts for training / inference are located in the `scripts` subfolder.

**Comment by zhizhangxian** [comment]
Sure, thanks!
