### ISSUE TITLE
ZeroDivisionError: float division by zero when slope is set to 0

### ISSUE THREAD

**Issue by mathmanu** [mapillary/inplace_abn#15]
I would like to use InPlaceABN with ReLU activation, but there is only support for "leaky_relu", "elu" and "none".

I tried to simulate ReLU by setting slope to 0, 
InPlaceABNSyncWrapper(planes, slope=0)

**but I got the following error:**
  File "/user/a0393608/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/user/a0393608/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/user/a0393608/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/user/a0393608/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/autograd/function.py", line 205, in wrapper
    outputs = fn(ctx, *tensor_args)
  File "/user/a0393608/files/work/code/vision/github/mapillary/inplace_abn/modules/functions.py", line 236, in backward
    _act_backward(ctx, z, dz)
  File "/user/a0393608/files/work/code/vision/github/mapillary/inplace_abn/modules/functions.py", line 57, in _act_backward
    _check(_ext.leaky_relu_cuda, x, 1. / ctx.slope)
**ZeroDivisionError: float division by zero**

Kindly help to use a ReLU activation.

**Comment by mathmanu** [comment]
I should have read the paper carefully.

In-Place Activated Batch Normalization I. A limitation
of the memory-reduction strategy described above is that
the last layer, namely CONV in the example, depends on
non-local quantities like x (or xˆ) for the computation of the
gradient. This makes the implementation of the approach
within standard frameworks somewhat cumbersome, because
the backward pass of any layer that follows φ, which
relies on the existence of z, has to somehow trigger its
recomputation. To render the implementation of the proposed
memory savings easier and self-contained, we suggest
an alternative strategy shown in Figure 2(d), which relies
on having only z as the saved buffer during the forward
pass, thus operating an in-place computation through the
BN layer (therefrom the paper’s title). By doing so, any
layer that follows the activation φ would have the information
for the gradient computation locally available. Having
stored z, we need to recompute xˆ backwards, for it will be
needed in the backward pass through the BN layer.4 However,
this operation is only possible if the activation func4This
solution can technically still be considered as a form of checkpointing,
but instead of recovering information forwards as in [4, 21], we
recover it backwards, thus bearing a similarity to reversible nets [9].
tion is invertible. **Even though this requirement does not
hold for RELU, i.e. one of the most dominantly used activation
functions, we show in § 4.1 that an invertible function
like LEAKY RELU [20] with a small slope works well as
a surrogate of RELU without compromising on the model
quality. **

**Comment by rotabulo** [comment]
@mathmanu Yes, the trick works only for invertible activations, so setting the slope to 0 is not feasible. 
I close the issue.

**Comment by lzrobots** [comment]
I copy the files in folder modules to this repo [https://github.com/speedinghzl/pytorch-segmentation-toolbox](url) and got following error:

Traceback (most recent call last):
  File "train.py", line 250, in <module>
    main()
  File "train.py", line 214, in main
    preds = model(images)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/Workspace/Seg/pytorch-segmentation-toolbox-1.0/networks/deeplabv3.py", line 161, in forward
    x = self.head(x)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/Workspace/Seg/pytorch-segmentation-toolbox-1.0/networks/deeplabv3.py", line 91, in forward
    feat1 = F.interpolate(self.conv1(x), size=(h, w), mode='bilinear', align_corners=True)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lz/Workspace/Seg/pytorch-segmentation-toolbox-1.0/libs/bn.py", line 119, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
  File "/home/lz/Workspace/Seg/pytorch-segmentation-toolbox-1.0/libs/functions.py", line 184, in forward
    running_var.mul_((1 - ctx.momentum)).add_(ctx.momentum * var * (float(count) / (count - 1)))
**ZeroDivisionError: float division by zero**

pytorch1.0
python3.7
cuda9.2

Thanks

**Comment by lzrobots** [comment]
seems the batch size of each GPU should be at least 2.

**Comment by lzrobots** [comment]
Thanks. The performance of the above experiments (deeplab v3) dropped to 74% by using the new pytorch1.0 version of inplace. Is there anything need to be careful when replacing the old version of inplace with pytorch 1.0 version? 
I only copied the files in ./modules to ./libs in https://github.com/speedinghzl/pytorch-segmentation-toolbox
