### ISSUE TITLE
cannot be installed with pip

### ISSUE THREAD

**Issue by ipScore** [mapillary/inplace_abn#162]
Hi  @ducksoup, I have tried to install inplace_abn with：
`pip install inplace-abn through PyPi`
or
`pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.11`
or
```
git clone https://github.com/mapillary/inplace_abn.git
cd inplace_abn
python setup.py install
cd scripts
pip install -r requirements.txt
```
All above ways have failed. Is there any suggested fix? Thanks.

**My Environment:**
```
Centos 7.6
CUDA 10.1
Nvidia Driver Version: 418.87.00
Anaconda3
Python 3.7.6 with GCC 7.3.0
PyTorch 1.4.0
```

**Error:**
```
Building wheels for collected packages: inplace-abn
  Building wheel for inplace-abn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /gs/home/jiangjie/anaconda/envs/torchEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e75fwfxp
       cwd: /tmp/pip-install-os12uckg/inplace-abn/
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-os12uckg/inplace-abn/setup.py", line 75, in <module>
      cmdclass={"build_ext": BuildExtension}
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 257, in build_extensions
      self._check_abi()
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 399, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 187, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 163, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos6-linux-gnu-c++']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for inplace-abn
  Running setup.py clean for inplace-abn
Failed to build inplace-abn
Installing collected packages: inplace-abn
    Running setup.py install for inplace-abn ... error
    ERROR: Command errored out with exit status 1:
     command: /gs/home/jiangjie/anaconda/envs/torchEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uexpgt_f/install-record.txt --single-version-externally-managed --compile --install-headers /gs/home/jiangjie/anaconda/envs/torchEnv/include/python3.7m/inplace-abn
         cwd: /tmp/pip-install-os12uckg/inplace-abn/
    Complete output (55 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-os12uckg/inplace-abn/setup.py", line 75, in <module>
        cmdclass={"build_ext": BuildExtension}
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 257, in build_extensions
        self._check_abi()
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 399, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 187, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 163, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/gs/home/jiangjie/anaconda/envs/torchEnv/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos6-linux-gnu-c++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /gs/home/jiangjie/anaconda/envs/torchEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-os12uckg/inplace-abn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uexpgt_f/install-record.txt --single-version-externally-managed --compile --install-headers /gs/home/jiangjie/anaconda/envs/torchEnv/include/python3.7m/inplace-abn Check the logs for full command output.

```

**Comment by ducksoup** [comment]
@ipScore If I understand the error logs, it appears that the setup process is not able to locate your C++ compiler correctly: `Command '['which', 'x86_64-conda_cos6-linux-gnu-c++']' returned non-zero exit status 1`.

Can you try creating a fresh minimal Anaconda environment and see if the installation works from there?

**Comment by ipScore** [comment]
Thanks @ducksoup. I create a new Anaconda envrionment and  it seems that my g++ 4.8.5 is not compatible for the present PyTorch.
However, since I don't have sudo privileges，is there any way for me to upgrade g++?

```
  52 2020-02-17T18:11:28,027                                  !! WARNING !!
  53 
  54 2020-02-17T18:11:28,027   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  55 2020-02-17T18:11:28,027   Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
  56 2020-02-17T18:11:28,028   Please use a compiler that is ABI-compatible with GCC 4.9 and above.
  57 2020-02-17T18:11:28,028   See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
  58 
  59 2020-02-17T18:11:28,028   See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
  60 2020-02-17T18:11:28,028   for instructions on how to install GCC 4.9 or higher.
  61 2020-02-17T18:11:28,028   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  62 
  63 2020-02-17T18:11:28,028                                 !! WARNING !!
  64 
  65 2020-02-17T18:11:28,028     warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
  66 2020-02-17T18:11:28,028   building 'inplace_abn._backend' extension
  67 2020-02-17T18:11:28,028   creating build/temp.linux-x86_64-3.8
  68 2020-02-17T18:11:28,028   creating build/temp.linux-x86_64-3.8/src


   6 2020-02-17T18:11:18,283 Entered build tracker: /tmp/pip-req-tracker-whpfsf84
   7 2020-02-17T18:11:18,283 Created temporary directory: /tmp/pip-install-rwd_9e28
   8 2020-02-17T18:11:18,284 Looking in indexes: https://pypi.doubanio.com/simple
   9 2020-02-17T18:11:18,286 1 location(s) to search for versions of inplace-abn:
  15 2020-02-17T18:11:18,464 Given no hashes to check 1 links for project 'inplace-abn': discarding no candidates
  16 2020-02-17T18:11:18,464 Using version 1.0.11 (newest of versions: 1.0.11)
  22 2020-02-17T18:11:18,519     Running command python setup.py egg_info
  23 2020-02-17T18:11:25,868     running egg_info
  30 2020-02-17T18:11:26,176     reading manifest template 'MANIFEST.in'
  34 2020-02-17T18:11:26,324 Building wheels for collected packages: inplace-abn
  35 2020-02-17T18:11:26,327   Created temporary directory: /tmp/pip-wheel-yqx28d0l
  36 2020-02-17T18:11:26,327   Destination directory: /tmp/pip-wheel-yqx28d0l
  38 2020-02-17T18:11:27,972   running bdist_wheel
  39 2020-02-17T18:11:27,973   running build
  40 2020-02-17T18:11:27,973   running build_py
  41 2020-02-17T18:11:27,985   creating build
  42 2020-02-17T18:11:27,985   creating build/lib.linux-x86_64-3.8
  43 2020-02-17T18:11:27,985   creating build/lib.linux-x86_64-3.8/inplace_abn
  44 2020-02-17T18:11:27,986   copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.8/inplace_abn
  45 2020-02-17T18:11:27,986   copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.8/inplace_abn
  46 2020-02-17T18:11:27,986   copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.8/inplace_abn
  47 2020-02-17T18:11:27,986   copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.8/inplace_abn
  68 2020-02-17T18:11:28,028   creating build/temp.linux-x86_64-3.8/src
  77 2020-02-17T18:11:28,355                    from src/inplace_abn_cpu.cpp:3:
  79 2020-02-17T18:11:28,355    #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
  90 2020-02-17T18:11:28,443    #error "You're running a too old version of GCC. We need GCC 5 or later."
  96 2020-02-17T18:11:30,145                    from src/inplace_abn_cpu.cpp:3:
   6 2020-02-17T18:11:18,283 Entered build tracker: /tmp/pip-req-tracker-whpfsf84
   7 2020-02-17T18:11:18,283 Created temporary directory: /tmp/pip-install-rwd_9e28
   8 2020-02-17T18:11:18,284 Looking in indexes: https://pypi.doubanio.com/simple
   9 2020-02-17T18:11:18,286 1 location(s) to search for versions of inplace-abn:
  15 2020-02-17T18:11:18,464 Given no hashes to check 1 links for project 'inplace-abn': discarding no candidates
  16 2020-02-17T18:11:18,464 Using version 1.0.11 (newest of versions: 1.0.11)
  22 2020-02-17T18:11:18,519     Running command python setup.py egg_info
  23 2020-02-17T18:11:25,868     running egg_info
  30 2020-02-17T18:11:26,176     reading manifest template 'MANIFEST.in'
  34 2020-02-17T18:11:26,324 Building wheels for collected packages: inplace-abn
  35 2020-02-17T18:11:26,327   Created temporary directory: /tmp/pip-wheel-yqx28d0l
  36 2020-02-17T18:11:26,327   Destination directory: /tmp/pip-wheel-yqx28d0l
  38 2020-02-17T18:11:27,972   running bdist_wheel
  39 2020-02-17T18:11:27,973   running build
  40 2020-02-17T18:11:27,973   running build_py
  41 2020-02-17T18:11:27,985   creating build
  42 2020-02-17T18:11:27,985   creating build/lib.linux-x86_64-3.8
  43 2020-02-17T18:11:27,985   creating build/lib.linux-x86_64-3.8/inplace_abn
  44 2020-02-17T18:11:27,986   copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.8/inplace_abn
  45 2020-02-17T18:11:27,986   copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.8/inplace_abn
  46 2020-02-17T18:11:27,986   copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.8/inplace_abn
  47 2020-02-17T18:11:27,986   copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.8/inplace_abn
  68 2020-02-17T18:11:28,028   creating build/temp.linux-x86_64-3.8/src
  77 2020-02-17T18:11:28,355                    from src/inplace_abn_cpu.cpp:3:
  79 2020-02-17T18:11:28,355    #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
  82 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/c10/core/ScalarType.h:6,
  83 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/c10/core/Scalar.h:9,
  84 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/ATen/core/TensorBody.h:7,
  85 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/ATen/Tensor.h:11,
  86 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/ATen/Context.h:4,
  87 2020-02-17T18:11:28,443                    from /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/incl     ude/ATen/ATen.h:5,
  88 2020-02-17T18:11:28,443                    from src/inplace_abn_cpu.cpp:3:
  89 2020-02-17T18:11:28,443   /gs/home/jiangjie/anaconda/envs/testenv/lib/python3.8/site-packages/torch/include/c10/util/TypeIndex     .h:31:2: error: #error "You're running a too old version of GCC. We need GCC 5 or later."
  90 2020-02-17T18:11:28,443    #error "You're running a too old version of GCC. We need GCC 5 or later."

```

**Comment by ipScore** [comment]
@ducksoup Thanks a lot. 
`#error "You're running a too old version of GCC. We need GCC 5 or later."` for c++ extension.
 I have installed inplace_abn successfully after upgrading gcc4.8.5 to gcc5.2.0 .

For those who don't have root access and are in a conda environment, do this:
`conda install -c psi4 gcc-5`
or download the desired gcc version and follow the instructions on GCC's homepage https://gcc.gnu.org/wiki/InstallingGCC:
```
tar xzf gcc-VERSION.tar.gz
cd gcc-VERSION
./contrib/download_prerequisites
cd ..
mkdir objdir
cd objdir
$PWD/../gcc-VERSION/configure --prefix=$HOME/GCC-VERSION --enable-languages=c,c++,fortran,go
make
make install
```

**Comment by ducksoup** [comment]
Glad you could solve, this will probably help other people encountering similar issues!
