### ISSUE TITLE
Incompatible with PyTorch 1.5.0

### ISSUE THREAD

**Issue by mattzque** [mapillary/inplace_abn#166]
After updating pytorch to 1.5.0 I get the following error using the InPlaceABN:

```
Traceback (most recent call last):
  File "abn_testing.py", line 19, in <module>
    module.forward(torch.tensor(np.zeros((4, 3, 128, 128), dtype=np.float32)))
  File "abn_testing.py", line 15, in forward
    x = self.abn(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/inplace_abn/abn.py", line 113, in forward
    self.training, self.momentum, self.eps, self.activation, self.activation_param)
  File "/usr/local/lib/python3.7/dist-packages/inplace_abn/functions.py", line 156, in inplace_abn
    training, momentum, eps, activation, activation_param, None)
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
```

> RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.

It seem to be caused by [this call to mark_dirty](https://github.com/mapillary/inplace_abn/blob/master/inplace_abn/functions.py#L90). If I modify the function so that it returns `x, running_mean, running_var` it won't raise this error, but it shouldn't return those.

I'm not sure how this should be fixed otherwise I would add a pull request.

Example to reproduce:

```
import numpy as np
import torch.nn as nn
import torch
from inplace_abn import InPlaceABN


class TestModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 64, (3, 3))
        self.abn = InPlaceABN(64)

    def forward(self, x):
        x = self.conv(x)
        x = self.abn(x)
        return x

module = TestModule()
module.forward(torch.tensor(np.zeros((4, 3, 128, 128), dtype=np.float32)))
```

**Comment by mattzque** [comment]
I found this issue that is probably causing this after the update: https://github.com/pytorch/pytorch/pull/33069

this probably indicates an issue to the way inplace_abn is using mark_dirty?

**Comment by mattzque** [comment]
v1.0.12 fixed it, thank you @ducksoup !
