### ISSUE TITLE
installation inside a Docker container

### ISSUE THREAD

**Issue by antran89** [mapillary/inplace_abn#181]
I would like to install inplace_abn inside a docker container from a docker file, but it shows the following error. But after logging into the container, I am able to install it fine. Could you please explain, and a possible solution for it?

```
ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-a5x5vu5s
       cwd: /tmp/pip-req-build-4_qo205_/
  Complete output (76 lines):
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/inplace_abn
  copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.6/inplace_abn
  copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.6/inplace_abn
  copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.6/inplace_abn
  copying inplace_abn/group.py -> build/lib.linux-x86_64-3.6/inplace_abn
  copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.6/inplace_abn
  running build_ext
  building 'inplace_abn._backend' extension
  creating /tmp/pip-req-build-4_qo205_/build/temp.linux-x86_64-3.6
  creating /tmp/pip-req-build-4_qo205_/build/temp.linux-x86_64-3.6/src
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-4_qo205_/setup.py", line 75, in <module>
      cmdclass={"build_ext": BuildExtension}
    File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
      build_ext.build_extensions(self)
    File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
      _build_ext.build_extension(self, ext)
    File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
      cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags
      cflags + _get_cuda_arch_flags(cflags))
    File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags
      capability = torch.cuda.get_device_capability()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 273, in get_device_capability
      prop = get_device_properties(device)
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 278, in get_device_properties
      _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
      _check_driver()
    File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 54, in _check_driver
      http://www.nvidia.com/Download/index.aspx""")
  AssertionError:
  Found no NVIDIA driver on your system. Please check that you
  have an NVIDIA GPU and installed a driver from
  http://www.nvidia.com/Download/index.aspx
  ----------------------------------------
  ERROR: Failed building wheel for inplace-abn
  Running setup.py clean for inplace-abn
Successfully built utm Rtree pyproj
Failed to build inplace-abn
ERROR: fastai 1.0.46 requires nvidia-ml-py3, which is not installed.
Installing collected packages: botocore, boto3, utm, pillow, Rtree, networkx, pyproj, geopandas, osmnx, joblib, geojson, inplace-abn
  Attempting uninstall: botocore
    Found existing installation: botocore 1.17.16
    Uninstalling botocore-1.17.16:
      Successfully uninstalled botocore-1.17.16
  Attempting uninstall: boto3
    Found existing installation: boto3 1.14.16
    Uninstalling boto3-1.14.16:
      Successfully uninstalled boto3-1.14.16
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.2.0
    Uninstalling Pillow-7.2.0:
      Successfully uninstalled Pillow-7.2.0
  Attempting uninstall: networkx
    Found existing installation: networkx 2.3
    Uninstalling networkx-2.3:
      Successfully uninstalled networkx-2.3
  Attempting uninstall: pyproj
    Found existing installation: pyproj 2.6.1.post1
    Uninstalling pyproj-2.6.1.post1:
      Successfully uninstalled pyproj-2.6.1.post1
  Attempting uninstall: geopandas
    Found existing installation: geopandas 0.8.0
    Uninstalling geopandas-0.8.0:
      Successfully uninstalled geopandas-0.8.0
  Attempting uninstall: joblib
    Found existing installation: joblib 0.16.0
    Uninstalling joblib-0.16.0:
      Successfully uninstalled joblib-0.16.0
    Running setup.py install for inplace-abn: started
    Running setup.py install for inplace-abn: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d8tbmstr/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/inplace-abn
         cwd: /tmp/pip-req-build-4_qo205_/
    Complete output (78 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/group.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.6/inplace_abn
    running build_ext
    building 'inplace_abn._backend' extension
    creating /tmp/pip-req-build-4_qo205_/build/temp.linux-x86_64-3.6
    creating /tmp/pip-req-build-4_qo205_/build/temp.linux-x86_64-3.6/src
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4_qo205_/setup.py", line 75, in <module>
        cmdclass={"build_ext": BuildExtension}
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/conda/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags
        capability = torch.cuda.get_device_capability()
      File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 273, in get_device_capability
        prop = get_device_properties(device)
      File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 278, in get_device_properties
        _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
      File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
        _check_driver()
      File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 54, in _check_driver
        http://www.nvidia.com/Download/index.aspx""")
    AssertionError:
    Found no NVIDIA driver on your system. Please check that you
    have an NVIDIA GPU and installed a driver from
    http://www.nvidia.com/Download/index.aspx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4_qo205_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d8tbmstr/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/inplace-abn Check the logs for full command output.
```

**Comment by nonword1** [comment]
I got the same problem!

**Comment by Qidian213** [comment]
I got the same problem! have you solved it ?

**Comment by antran89** [comment]
@Qidian213  I cannot install during the building process, but can write bootstrap script to install it after docker image was built

**Comment by ducksoup** [comment]
@Qidian213 @antran89 Sorry for the late response. The issue you are seeing is due to the fact that the Pytorch extension build scripts try to access the GPU at build time, but that doesn't work correctly when building docker containers. A work-around for this issue is to set the following environmental variable in the docker build script: `TORCH_CUDA_ARCH_LIST="{gpu arch}"`, where `{gpu arch}` is e.g. `6.0` if you are using Pascal GPUs and so on.

Note that this same work-around is also necessary to build `inplace_abn` on machines where the GPU version of Pytorch is installed, but no GPU is actually available.

**Comment by Qidian213** [comment]
@ducksoup  Thanks,  I have solved this problem.
