### ISSUE TITLE
How to install this package on Pytorch 1.6?

### ISSUE THREAD

**Issue by NoOneUST** [mapillary/inplace_abn#197]
I met the following problem:

```
(base) -bash-4.2$ cd inplace_abn
(base) -bash-4.2$ ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  equation.svg  include  inplace_abn  inplace_abn.png  LICENSE  licenses.csv  MANIFEST.in  README.md  requirements.txt  scripts  setup.cfg  setup.py  src
(base) -bash-4.2$ python setup.py install
running install
running bdist_egg
running egg_info
creating inplace_abn.egg-info
writing inplace_abn.egg-info/PKG-INFO
writing dependency_links to inplace_abn.egg-info/dependency_links.txt
writing top-level names to inplace_abn.egg-info/top_level.txt
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/inplace_abn
copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
running build_ext
building 'inplace_abn._backend' extension
creating /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7
creating /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src
Emitting ninja build file /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] c++ -MMD -MF /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/utils.o.d -pthread -B /data/lwangcg/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda-10.1/include -I/usr/local/cuda-10.1/include -fPIC -DWITH_CUDA=1 -I/export/data/lwangcg/inplace_abn/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/export/data/lwangcg/anaconda3/include/python3.7m -c -c /export/data/lwangcg/inplace_abn/src/utils.cpp -o /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/utils.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2/4] c++ -MMD -MF /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn_cpu.o.d -pthread -B /data/lwangcg/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda-10.1/include -I/usr/local/cuda-10.1/include -fPIC -DWITH_CUDA=1 -I/export/data/lwangcg/inplace_abn/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/export/data/lwangcg/anaconda3/include/python3.7m -c -c /export/data/lwangcg/inplace_abn/src/inplace_abn_cpu.cpp -o /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn_cpu.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[3/4] /usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA=1 -I/export/data/lwangcg/inplace_abn/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/export/data/lwangcg/anaconda3/include/python3.7m -c -c /export/data/lwangcg/inplace_abn/src/inplace_abn_cuda.cu -o /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o
/usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA=1 -I/export/data/lwangcg/inplace_abn/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/export/data/lwangcg/anaconda3/include/python3.7m -c -c /export/data/lwangcg/inplace_abn/src/inplace_abn_cuda.cu -o /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:5052:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:5073:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:6725:95:   required from here
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:1067:1: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
 ^     ~~~~~~~~~
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:5052:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:5073:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.h:6730:95:   required from here
/usr/local/GNU/gcc-8.3.0/include/c++/8.3.0/bits/basic_string.tcc:1067:1: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
[4/4] c++ -MMD -MF /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn.o.d -pthread -B /data/lwangcg/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda-10.1/include -I/usr/local/cuda-10.1/include -fPIC -DWITH_CUDA=1 -I/export/data/lwangcg/inplace_abn/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/export/data/lwangcg/anaconda3/include/python3.7m -c -c /export/data/lwangcg/inplace_abn/src/inplace_abn.cpp -o /export/data/lwangcg/inplace_abn/build/temp.linux-x86_64-3.7/src/inplace_abn.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149,
                 from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /export/data/lwangcg/inplace_abn/src/inplace_abn.cpp:3:
/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    cmdclass={"build_ext": BuildExtension}
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/export/data/lwangcg/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by bsugerman** [comment]
I'm running python 3.7 and pytorcch 1.6 and did not have any problem installing or running this.

**Comment by DuongTran1708** [comment]
You are using gcc-8.3.0, you should downgrade to 7.5.0. I compiled with python 3.7, pytorch 1.7.0, then it worked.

**Comment by valencebond** [comment]
same problem. I can install it without error. But when `from inplace_abn import InPlaceABN`, the same error occurs with python 3.7 pytorch1.7 gcc7.5


> inplace_abn-1.1.1.dev2+g938ffd2-py3.7-linux-x86_64.egg/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by valencebond** [comment]
> same problem. I can install it without error. But when `from inplace_abn import InPlaceABN`, the same error occurs with python 3.7 pytorch1.7 gcc7.5
> 
> > inplace_abn-1.1.1.dev2+g938ffd2-py3.7-linux-x86_64.egg/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

fix it with right nvcc version

**Comment by ericdai713** [comment]
> > same problem. I can install it without error. But when `from inplace_abn import InPlaceABN`, the same error occurs with python 3.7 pytorch1.7 gcc7.5
> > > inplace_abn-1.1.1.dev2+g938ffd2-py3.7-linux-x86_64.egg/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
> 
> fix it with right nvcc version

I have the same problem,
Can you tell me which nvcc version you use?
Thank you
