### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by xufengfan96** [mapillary/inplace_abn#212]
when I install inplace_abn with pip install. I get the mistake:
ERROR: Command errored out with exit status 1:
   command: /home/lab505/anaconda3/envs/mvsnerf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e8k9s5gi
       cwd: /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
  running build_ext
  building 'inplace_abn._backend' extension
  creating /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7
  creating /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src
  Emitting ninja build file /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/4] /usr/local/cuda-10.2/bin:/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o.d -DWITH_CUDA=1 -I/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/TH -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/bin:/include -I/home/lab505/anaconda3/envs/mvsnerf/include/python3.7m -c -c /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/inplace_abn_cuda.cu -o /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
  FAILED: /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o
  /usr/local/cuda-10.2/bin:/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o.d -DWITH_CUDA=1 -I/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/TH -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/bin:/include -I/home/lab505/anaconda3/envs/mvsnerf/include/python3.7m -c -c /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/inplace_abn_cuda.cu -o /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
  /bin/sh: 1: /usr/local/cuda-10.2/bin:/bin/nvcc: not found
  [2/4] c++ -MMD -MF /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/utils.o.d -pthread -B /home/lab505/anaconda3/envs/mvsnerf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=1 -I/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/TH -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/bin:/include -I/home/lab505/anaconda3/envs/mvsnerf/include/python3.7m -c -c /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/utils.cpp -o /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/utils.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  [3/4] c++ -MMD -MF /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cpu.o.d -pthread -B /home/lab505/anaconda3/envs/mvsnerf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=1 -I/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/TH -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/bin:/include -I/home/lab505/anaconda3/envs/mvsnerf/include/python3.7m -c -c /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/inplace_abn_cpu.cpp -o /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn_cpu.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  [4/4] c++ -MMD -MF /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn.o.d -pthread -B /home/lab505/anaconda3/envs/mvsnerf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=1 -I/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/TH -I/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/bin:/include -I/home/lab505/anaconda3/envs/mvsnerf/include/python3.7m -c -c /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/inplace_abn.cpp -o /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/build/temp.linux-x86_64-3.7/src/inplace_abn.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                   from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                   from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                   from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                   from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                   from /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                   from /tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/src/inplace_abn.cpp:3:
  /home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   #pragma omp parallel for if ((end - begin) >= grain_size)
 
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
      env=env)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
 
  The above exception was the direct cause of the following exception:
 
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_xhnlwk4/inplace-abn_a555f7ca85414f6a9c30724432f4cc2f/setup.py", line 75, in <module>
      cmdclass={"build_ext": BuildExtension}
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
      build_ext.build_extensions(self)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
      with_cuda=with_cuda)
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "/home/lab505/anaconda3/envs/mvsnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for inplace-abn

After I read some issues I find it may caused by ninja or nvcc.However I installed them and it didn't work.Here is the conda list:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
absl-py                   0.14.1                   pypi_0    pypi
aiohttp                   3.7.4.post0              pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.9.30            h06a4308_1    defaults
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.5.30        py37h06a4308_0    defaults
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.7                    pypi_0    pypi
config-argparse           0.3.3                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1    defaults
cudnn                     7.6.5                cuda10.2_0    defaults
cycler                    0.10.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0    defaults
fsspec                    2021.10.0                pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gmp                       6.2.1                h2531618_2    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.41.0                   pypi_0    pypi
idna                      3.2                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        4.8.1                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libiconv                  1.15                 h63c8f33_5    defaults
libidn2                   2.3.2                h7f8727e_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libuv                     1.40.0               h7b6447c_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
lpips                     0.1.4                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1    defaults
markdown                  3.3.4                    pypi_0    pypi
matplotlib                3.4.3                    pypi_0    pypi
mkl                       2021.3.0           h06a4308_520    defaults
mkl-service               2.4.0            py37h7f8727e_0    defaults
mkl_fft                   1.3.0            py37h42c9631_2    defaults
mkl_random                1.2.2            py37h51133e4_0    defaults
multidict                 5.2.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2.2                 pypi_0    pypi
numpy                     1.20.3           py37hf144106_0    defaults
numpy-base                1.20.3           py37h74d4b33_0    defaults
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46                     py37_0    defaults
opencv-python             4.5.3.56                 pypi_0    pypi
openh264                  2.1.0                hd408876_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   1.1.1l               h7f8727e_0    defaults
packaging                 21.0                     pypi_0    pypi
pillow                    8.3.1            py37h2c7a002_0    defaults
pip                       21.0.1           py37h06a4308_0    defaults
protobuf                  3.18.1                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydeprecate               0.3.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.11               h12debd9_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.8.0           py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-lightning         1.3.5                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0    defaults
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tifffile                  2021.10.10               pypi_0    pypi
tk                        8.6.11               h1ccaba5_0    defaults
torchaudio                0.8.0                      py37    pytorch
torchmetrics              0.5.1                    pypi_0    pypi
torchvision               0.9.0                py37_cu102    pytorch
tqdm                      4.62.3                   pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
urllib3                   1.26.7                   pypi_0    pypi
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1    defaults
xz                        5.2.5                h7b6447c_0    defaults
yarl                      1.7.0                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults

So anyone knows why?Help!!!

**Comment by Ran-Ding** [comment]
I also meet with this problem. Maybe we can communicate with each other. My email is ran.ding@tum.de

**Comment by william0620** [comment]
@Ran-Ding Have you solved it

**Comment by plsky36** [comment]
me too. Have you solved it?

**Comment by Yummy198913** [comment]
@plsky36 @william2ai @Ran-Ding me, too, have you solved it ? please help!!!

**Comment by plsky36** [comment]
I solved it.It may connect with your your installation packages and other dependencies are related to your installation source.You can try the instruction- conda install -c esri inplace-abn        python≥3.7> @plsky36 @william2ai @Ran-Ding me, too, have you solved it ? please help!!!

**Comment by Yummy198913** [comment]
> I solved it.It may connect with your your installation packages and other dependencies are related to your installation source.You can try the instruction- conda install -c esri inplace-abn python≥3.7> [@plsky36](https://github.com/plsky36) [@william2ai](https://github.com/william2ai) [@Ran-Ding](https://github.com/Ran-Ding) me, too, have you solved it ? please help!!!


Really appreciate for you advice, recently i have figured out that most of these build error are caused by cuda environment settings. I tried to install cuda in my conda environment and set the CUDA_HOME but it  didn`t work, now I install a higher version of cuda on the computer with a non-root account and set environment variables to resolve these build errors.
