### ISSUE TITLE
An import error 

### ISSUE THREAD

**Issue by fsted** [mapillary/inplace_abn#220]
hello, i got an import error:
When 
`import inplace_abn`
It tells :
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in <module>
    from . import _backend
ImportError: /home/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda6detail20canUse32BitIndexMathERKNS_6TensorEl
`
This confuses me, what to do with it,Thanks

**Comment by JackyLin7414** [comment]
I also have same problem
My pyorch version is 1.7.0

**Comment by inphantasm** [comment]
I have a similar one:
  File "D:\Anaconda\lib\site-packages\inplace_abn\__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\Anaconda\lib\site-packages\inplace_abn\abn.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "D:\Anaconda\lib\site-packages\inplace_abn\functions.py", line 8, in <module>
    from . import _backend
ImportError: DLL load failed: 找不到指定的程序。

**Comment by wzkwzk1998** [comment]
I also have this problem
/site-packages/inplace_abn/_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm

**Comment by walking-shadow** [comment]
> hello, i got an import error: When `import inplace_abn` It tells : Traceback (most recent call last): File "", line 1, in File "/home/lib/python3.7/site-packages/inplace_abn/**init**.py", line 1, in from .abn import ABN, InPlaceABN, InPlaceABNSync File "/home/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in from .functions import inplace_abn, inplace_abn_sync File "/home/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in from . import _backend ImportError: /home/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda6detail20canUse32BitIndexMathERKNS_6TensorEl
> 
> This confuses me, what to do with it,Thanks

You can refer to Requirement Note 2, which says NOTE 2: we are only able to provide support for Linux platforms and CUDA versions >= 10.0, so it won't work in windows platform.

**Comment by xiaohulihutu** [comment]
> > hello, i got an import error: When `import inplace_abn` It tells : Traceback (most recent call last): File "", line 1, in File "/home/lib/python3.7/site-packages/inplace_abn/**init**.py", line 1, in from .abn import ABN, InPlaceABN, InPlaceABNSync File "/home/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in from .functions import inplace_abn, inplace_abn_sync File "/home/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in from . import _backend ImportError: /home/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda6detail20canUse32BitIndexMathERKNS_6TensorEl
> > This confuses me, what to do with it,Thanks
> 
> You can refer to Requirement Note 2, which says NOTE 2: we are only able to provide support for Linux platforms and CUDA versions >= 10.0, so it won't work in windows platform.

Thats very interesting because when i run in windows, i dont have this error, but when i run in WSL this error poped up. And i m totally confuse now
