### ISSUE TITLE
Import issue: Undefined symbol

### ISSUE THREAD

**Issue by curt-tigges** [mapillary/inplace_abn#224]
When attempting to import Inplace-ABN version 1.1.0, I get the following error:

```
>>> from inplace_abn import InPlaceABN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in <module>
    from . import _backend
ImportError: /home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```

I am using CUDA 11.2 and PyTorch 1.8.2. The Inplace-ABN files were compiled with GCC 10.

**Comment by hubblezhang** [comment]
> When attempting to import Inplace-ABN version 1.1.0, I get the following error:
> 
> ```
> >>> from inplace_abn import InPlaceABN
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
>     from .abn import ABN, InPlaceABN, InPlaceABNSync
>   File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in <module>
>     from .functions import inplace_abn, inplace_abn_sync
>   File "/home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in <module>
>     from . import _backend
> ImportError: /home/curttigges/miniconda3/envs/pytorch-dl/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
> ```
> 
> I am using CUDA 11.2 and PyTorch 1.8.2. The Inplace-ABN files were compiled with GCC 10.

I update my cuda-10.1 to cuda-10.2, then it works.

**Comment by QinghuanWei** [comment]
> 

so are you update your cuda-11.2 to 10.2 ? i get the same error by using cuda-11.0
