### ISSUE TITLE
load cpp extension error

### ISSUE THREAD

**Issue by hypercost** [mapillary/inplace_abn#38]
```
Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/simple/zj13/inplace_abn/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
TypeError: load() got an unexpected keyword argument 'extra_cuda_cflags'
```

Pytorch: 0.4.0
CUDA: 8.0
GCC: 4.8.4

**Comment by rotabulo** [comment]
@ksnzh does it work if you run it without debugger ?

**Comment by ksnzh** [comment]
@rotabulo I will try to run directly later. Thanks to your reply.

**Comment by ksnzh** [comment]
I got the same error by just running `test_imagenet.py`.
And I have installed ninja-build.

```
/opt/conda/bin/python2.7 /simple/zj13/inplace_abn/test_imagenet.py
Traceback (most recent call last):
  File "/simple/zj13/inplace_abn/test_imagenet.py", line 15, in <module>
    import models
  File "/simple/zj13/inplace_abn/models/__init__.py", line 1, in <module>
    from .resnext import *
  File "/simple/zj13/inplace_abn/models/resnext.py", line 7, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "/simple/zj13/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/simple/zj13/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/simple/zj13/inplace_abn/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
TypeError: load() got an unexpected keyword argument 'extra_cuda_cflags'
```

**Comment by rotabulo** [comment]
@ksnzh this looks more an issue independent from our code. Did you try with a more recent version of cuda?
