### ISSUE TITLE
Strange error when use the pretrained resnet-38 model

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#46]
I find the error is related an extra added branch that I use,

```
    def forward(self, img):
        out = self.mod1(img)
        out = self.mod2(self.pool2(out))
        out = self.mod3(self.pool3(out))
        out = self.mod4(out)
        out = self.mod5(out)
        out = self.mod6(out)
        out_dsn = self.dsn(out)
        out = self.mod7(out)
        out = self.bn_out(out)
        out = self.context(out)
        out = self.cls(out)
        return [out_dsn, out]
```

The error is removed if I replace the last output  **[out_dsn, out]** with  **[out, out]**.

This bug seems strange?

```
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main()
  File "train.py", line 147, in main
    loss.backward()
  File "/root/miniconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

Have anyone meets the above problem?

I do not add anything to the original code and just try to train the resnet38 models.

**Comment by PkuRainBow** [comment]
@rotabulo Could you help me?

**Comment by DanielDagnino** [comment]
Did you solve the problem? I have the same problem:
```
    loss.backward()
  File "/HOME/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/HOME/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
I am using Pytorch 0.5 version.

**Comment by PkuRainBow** [comment]
@DanielDagnino  I still have not solved this problem.... Hope @rotabulo @ducksoup could help us.

**Comment by DanielDagnino** [comment]
@PkuRainBow I solve the problem in my particular case, it was due to a nn.ReLU(inplace=True) that I was using, it is not compatible with the InPlaceABN. I recommend you to change any inplace=True to False in the layers of your model.

**Comment by PkuRainBow** [comment]
@DanielDagnino I have not used any other inplace operation.

**Comment by ducksoup** [comment]
@PkuRainBow can you show us the contents of you dsn module to help you debug your issue?

**Comment by rotabulo** [comment]
@PkuRainBow can you try `self.dsn(out.clone())`  ?

**Comment by PkuRainBow** [comment]
@rotabulo Ok, I will try it soon.

**Comment by rotabulo** [comment]
Closing due to inactivity.
