### ISSUE TITLE
error for test_vistas.py

### ISSUE THREAD

**Issue by mingminzhen** [mapillary/inplace_abn#49]
I try the test_vistas.py, something is wrong.
```
Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 311, in <module>
    main()
  File "test_vistas_single_gpu.py", line 188, in main
    probs, preds = model(img, scales, args.flip)
  File "/home/mingmin/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "test_vistas_single_gpu.py", line 135, in forward
    sem_logits = self._network(x, scale)
  File "test_vistas_single_gpu.py", line 117, in _network
    x_up = functional.upsample(x, size=scaled_size, mode="bilinear")
  File "/home/mingmin/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1891, in upsample
    return interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/mingmin/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1985, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
TypeError: 'float' object cannot be interpreted as an integer
```
Then i modify the code in the function _network(self, x, scale):
``` scaled_size = [s * scale for s in x.shape[-2:]]```
to
```            scaled_size = [int(s * scale) for s in x.shape[-2:]]

```
No error occurs. But the output image is wrong. No right segmentation result.
Can you help check the segmentation model and code ?

**Comment by rotabulo** [comment]
@mingminzhen thank you for reporting this issue. We should cast the scaled_size to int, but I would do it with `round`. Anyway, I was using the test_vistas script with no problems to predict Vistas images. Are you running the same?

**Comment by rotabulo** [comment]
@mingminzhen when you download the samples you get in the same folder both the image and the ground-truth segmentation. Is it possible that the image you show here is actually the network applied to the ground-truth annotation?

**Comment by mingminzhen** [comment]
I copy the images in the directory: /home/mingmin/data/mapillary/samples.
The groundtruth is not copied.

**Comment by rotabulo** [comment]
@mingminzhen this is the output I get:

![tlxglvwxygudubfkjy1uoq](https://user-images.githubusercontent.com/28045295/44989607-b0217680-af8e-11e8-8e6e-013f88ef6c0a.png)

**Comment by mingminzhen** [comment]
It's weird. I didn't modify anything. I use cuda9.2 and pytorch 4.0.

**Comment by rotabulo** [comment]
@mingminzhen can you try with `test_vistas_single_gpu.py`?

**Comment by mingminzhen** [comment]
@rotabulo I copy the image (samples/Asia/tlxGlVwxyGUdUBfkjy1UOQ.jpg) to another dir. And test it.

**Comment by mingminzhen** [comment]
https://drive.google.com/open?id=1bpSF5Wpj9MTwC3k-n87_KXFQPZeyk5ZH   This is the image i put in a dir called test (only one image in this dir).

**Comment by rotabulo** [comment]
On my end this keeps working..

![test](https://user-images.githubusercontent.com/28045295/44992227-f084f280-af96-11e8-8159-eb5c73acf8ac.png)

**Comment by mingminzhen** [comment]
Is it possible that the pretrained model is different from which you use?
I check the code carefully. It seems no errors in the code.

**Comment by rotabulo** [comment]
@mingminzhen I tested with both pytorch v0.4.1 and v0.4.0 and I have cuda 9.2 too. It works in all cases.

**Comment by rotabulo** [comment]
@mingminzhen I am using the one we provide on the webpage and also checked that the md5 sum matches.

**Comment by mingminzhen** [comment]
@rotabulo I try to change another machine and test it. It gets the same output. I test it on Anacoda 2, python3.6, pytorch v0.4.1 and cuda9.2. I feel so weird why it shows wrong output.

**Comment by rotabulo** [comment]
@mingminzhen what GPUs are you using?

**Comment by mingminzhen** [comment]
@rotabulo i use one 1080 ti.

**Comment by rotabulo** [comment]
@mingminzhen I tried also with a 1070 and it worked. I don't think it's the GPU.

**Comment by mingminzhen** [comment]
@rotabulo I use the cudnn7.2.1.38. I will check it again.

**Comment by mingminzhen** [comment]
@rotabulo  Hi, I test the gpu code by following code:
```
import torch
import inplace_abn

input = torch.randn(100,100,150,200).cuda()
print('x:',input.size())


xsum1 = input.sum(dim=0).sum(dim=-1).sum(dim=-1)/(input.size(0)*input.size(2)*input.size(3))
print('sum1:',xsum1.size())
print('xsum:', xsum1.sum(),xsum1[0], xsum1[1])


xsum, xssum = inplace_abn.mean_var(input)
print('xsum:',xsum.sum(), xsum[0], xsum[1])
```
The result is as follows:
```
x: torch.Size([100, 100, 150, 200])
sum1: torch.Size([100])
xsum: tensor(-0.0041, device='cuda:0') tensor(-0.0000, device='cuda:0') tensor(-0.0007, device='cuda:0')
xsum: tensor(-284.8568, device='cuda:0') tensor(-0.0041, device='cuda:0') tensor(211.0134, device='cuda:0')

```

It seems there is error for the cuda code in mean_var  cuda implementation code.
Can you help check that? 
In addition, the cpu code works well.  
```
import torch
import inplace_abn

input = torch.randn(100,100,150,200)
print('x:',input.size())


xsum1 = input.sum(dim=0).sum(dim=-1).sum(dim=-1)/(input.size(0)*input.size(2)*input.size(3))
print('sum1:',xsum1.size())
print('xsum:', xsum1.sum(),xsum1[0], xsum1[1])


xsum, xssum = inplace_abn.mean_var(input)
print('xsum:',xsum.sum(), xsum[0], xsum[1])
```
The result is 

```
x: torch.Size([100, 100, 150, 200])
sum1: torch.Size([100])
xsum: tensor(-0.0015) tensor(-0.0008) tensor(-0.0007)
xsum: tensor(-0.0015) tensor(-0.0008) tensor(-0.0007)
```

**Comment by mingminzhen** [comment]
@rotabulo I try to use cpu to do test. it works well.

**Comment by rotabulo** [comment]
@mingminzhen I checked the test code you posted, and it works on our side, i.e. we experience no issue. I invite you to try with some other machine/gpu.

**Comment by mingminzhen** [comment]
@rotabulo  I found the reason for that at last. It's because my driver is 390, but it's insufficient for cuda9.2 runtime. But there is no error shown in the code. So i suggest add some error check code for each kernel function.
```
  cudaError_t cudaError = cudaGetLastError();
  if(cudaError != cudaSuccess)
  {
    printf("  cudaGetLastError() returned %d: %s\n", cudaError, cudaGetErrorString(cudaError));
  }
```
This will be very useful!
