### ISSUE TITLE
Problem with setting GPU different from "cuda:0"

### ISSUE THREAD

**Issue by bonlime** [mapillary/inplace_abn#52]
Hi. I've tried to train model using your InPlaceBN, but after I move model & data to 'cuda:1' I have an error during training:

```
Traceback (most recent call last):
  File "torch_train.py", line 375, in <module>
    main()
  File "torch_train.py", line 339, in main
    metrics, summary_writer=None)
  File "torch_train.py", line 104, in train
    outputs = model(x)
  File "/home/zakirov/torch-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zakirov/kaggle_salt/model_zoo/ternausnet2.py", line 103, in forward
    conv2 = self.conv2(self.pool(conv1))
  File "/home/zakirov/torch-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zakirov/torch-py3/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/zakirov/torch-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zakirov/kaggle_salt/modules/residual.py", line 80, in forward
    bn1 = self.bn1(x)
  File "/home/zakirov/torch-py3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zakirov/kaggle_salt/modules/bn.py", line 108, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
  File "/home/zakirov/kaggle_salt/modules/functions.py", line 102, in forward
    running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:233
```
I found the source of this bug: 
After loading `_backend` in [functions.py#L9](https://github.com/mapillary/inplace_abn/blob/master/modules/functions.py#L9)
When `_backend.mean_var` is called in [functions.py#L94](https://github.com/mapillary/inplace_abn/blob/master/modules/functions.py#L94) it puts all new variables into `cuda:0` by default. 
That causes problem in the next line, because `running_mean` is located at the GPU specified for the model. 
I checked the pytorch sources, but didn't find if it's possible to specify default device.Do you have any ideas how to fix it?

**Comment by rotabulo** [comment]
@bonlime thank you for spotting this issue. I think it's a bug in Aten, but we are checking it. Nevertheless, the reason why we never encounter it is because DataParallel changes the default gpu per thread (https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/parallel_apply.py#L55). By doing so, everything works. As a temporarily workaround you could run the forward pass within  ` with torch.cuda.device(device):`

**Comment by ezyang** [comment]
You can fix this by replacing anywhere you do this:

```
  auto mean = at::empty(x.type(), {chn});
```

with

```
  auto mean = at::empty({chn}, x.options());
```

The "type" of a tensor doesn't include what device it's on; but the options do. This will preserve the device.

I also agree the suggested temporary workaround will work.

**Comment by rotabulo** [comment]
@ezyang thank you for the suggestion. We will try it.

**Comment by bonlime** [comment]
@rotabulo  @ezyang 
I just found that using `torch.cuda.set_device(1)` helps to fix this problem.
Maybe it was my bad and you don't need to change the code

**Comment by bonlime** [comment]
Thanks!
