### ISSUE TITLE
Unable to `import modules` which makes it impossible to train or test the code

### ISSUE THREAD

**Issue by Spandan-Madan** [mapillary/inplace_abn#56]
```
Cuda Version: 8.0
Pytorch version: 0.4.1 
GCC version: 5.2.0
```
The "modules" module cannot be imported, which leads to errors all across the board. Here's the stack trace-

```
>>> import modules
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/graphics/toyota-pytorch/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/data/graphics/toyota-pytorch/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/data/graphics/toyota-pytorch/inplace_abn/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 494, in load
    with_cuda=with_cuda)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 670, in _jit_compile
    return _import_module_from_library(name, build_directory)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 753, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/afs/csail.mit.edu/u/s/smadan/miniconda3/envs/test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /tmp/torch_extensions/inplace_abn/inplace_abn.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

When I try to run the inference using `test_vistas.py`, it tries to `import modules` which again gives the same issue. 

Can someone please help out with this?

**Comment by rotabulo** [comment]
@Spandan-Madan can you upgrade cuda to at least 9.0 ?

**Comment by Spandan-Madan** [comment]
@rotabulo Looked more into this. It seems to be a GCC versioning issue.

What version of GCC did you use when compiling? I'm on 5.2.

**Comment by rotabulo** [comment]
@Spandan-Madan please consider the new version of our code that we released today, in case you did not solve the issue in the meanwhile. Closing the issue by now.
