### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Dennis-YB** [mapillary/inplace_abn#67]
Excuse me,when I run this program,there is an error
```
python test_vistas.py /home/dilu04/inplace_abn/wide_resnet38_deeplab_vistas.pth.tar /home/dilu04/inplace_abn/inputimg /home/dilu04/inplace_abn/outputimg
['/home/dilu04/inplace_abn/wide_resnet38_deeplab_vistas.pth.tar', '/home/dilu04/inplace_abn/inputimg', '/home/dilu04/inplace_abn/outputimg', '--world-size', '1', '--rank', '0']
Traceback (most recent call last):
  File "/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 576, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/home/dilu04/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/dilu04/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 14, in <module>
    import models
  File "/home/dilu04/inplace_abn/models/__init__.py", line 1, in <module>
    from .resnext import *
  File "/home/dilu04/inplace_abn/models/resnext.py", line 7, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "/home/dilu04/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/dilu04/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/dilu04/inplace_abn/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 501, in load
    _build_extension_module(name, build_directory)
  File "/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 582, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/dilu04/anaconda3/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/dilu04/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/dilu04/anaconda3/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(99): error: class "at::Tensor" has no member "options"

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(99): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(100): error: class "at::Tensor" has no member "options"

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(100): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(202): error: class "at::Tensor" has no member "options"

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(202): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(203): error: class "at::Tensor" has no member "options"

/home/dilu04/inplace_abn/modules/src/inplace_abn_cuda.cu(203): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

8 errors detected in the compilation of "/tmp/tmpxft_00000835_00000000-6_inplace_abn_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.
```

*********************
My confige is pytorch 0.4,cuda 9.0,gcc 4.9,g++ 4.9,ubuntu 16.04,how to solve it?

**Comment by rotabulo** [comment]
@Dennis-YB  we have released a new version of our code that supports PyTorch v1.0 and multi-process synchronization. Can you try with that?

**Comment by ChenglongWang** [comment]
I had same issue. Pytorch v1.0 with CUDA>=9.0 solved this issue.

**Comment by rotabulo** [comment]
I am closing the issue. Please re-open it if the problem persists with the new release and newer version of CUDA.
