### ISSUE TITLE
ImportError: /tmp/torch_extensions/inplace_abn/inplace_abn.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by charlesCXK** [mapillary/inplace_abn#71]
```shell
chen@omnisky:~/project/nyu_dv2$ ./run.sh 
/home/chen/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:118: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    from graph import *
  File "../graph/__init__.py", line 11, in <module>
    from .res_deeplabv3 import Res_Deeplab
  File "../graph/res_deeplabv3.py", line 16, in <module>
    from .inplace_abn.modules import InPlaceABN, InPlaceABNSync
  File "../graph/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "../graph/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "../graph/inplace_abn/modules/functions.py", line 17, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/chen/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/home/chen/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 690, in _jit_compile
    return _import_module_from_library(name, build_directory)
  File "/home/chen/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 774, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/chen/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/chen/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /tmp/torch_extensions/inplace_abn/inplace_abn.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs ```

I got this error above when using Inplace_abn. 
My environment is listed below:
gcc: 5.4.0, 
os: ubuntu 16.04,
pytorch : 0.4.1,
CUDA: 9.1
How can I solve this problem? I can not find the answer online. Thank you very much!

**Comment by charlesCXK** [comment]
Oh, my problem has been solved.
This is mainly because of pytorch version dismatch.
When I reinstalled pytorch 0.4.0, the problem was almost gone.

refer here:
[https://github.com/NVIDIA/vid2vid/issues/25](https://github.com/NVIDIA/vid2vid/issues/25)

Thank you and I am sorry to bother you.
