### ISSUE TITLE
Has anyone tried the program for Windows?

### ISSUE THREAD

**Issue by MuyanXiao** [mapillary/inplace_abn#72]
I'm trying to set up a windows environment for the testing program. 
I'm using gcc6.3.0, cuda9.2, torch0.4.1, ninja 1.8.2.post2.

I got the following error:

C:\Python36\lib\site-packages\torch\utils\cpp_extension.py:92: UserWarning: Error checking compiler version: Command '['c++']' returned non-zero exit status 1.
  warnings.warn('Error checking compiler version: {}'.format(error))
C:\Python36\lib\site-packages\torch\utils\cpp_extension.py:118: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    import models
  File "C:\zhpcui\muyan_xiao\Code_Models\Code\models\__init__.py", line 1, in <module>
    from .resnext import *
  File "C:\zhpcui\muyan_xiao\Code_Models\Code\models\resnext.py", line 7, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "C:\zhpcui\muyan_xiao\Code_Models\Code\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\zhpcui\muyan_xiao\Code_Models\Code\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\zhpcui\muyan_xiao\Code_Models\Code\modules\functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "C:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "C:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 678, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 860, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by rotabulo** [comment]
@MuyanXiao we are not interested in providing compatibility with Windows, but if you find any solution, please post it here. Note that today we released a new version of our code that supports PyTorch v1.0. Please use the most recent version.
