### ISSUE TITLE
error: namespace "thrust::cuda" has no member "par"

### ISSUE THREAD

**Issue by b-hahn** [mapillary/inplace_abn#81]
Hi, 
I'm trying to run test_vistas.py and get the following error message:

```
['weights/wide_resnet38_deeplab_vistas.pth.tar', '/home/developer/datasets/mapillary_vistas/validation/images/', 'output/', '--world-size', '2', '--rank', '0']
['weights/wide_resnet38_deeplab_vistas.pth.tar', '/home/developer/datasets/mapillary_vistas/validation/images/', 'output/', '--world-size', '2', '--rank', '1']
Traceback (most recent call last):
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 14, in <module>
    import models
  File "/home/developer/inplace_abn/models/__init__.py", line 1, in <module>
    from .resnext import *
  File "/home/developer/inplace_abn/models/resnext.py", line 7, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "/home/developer/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/developer/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/developer/inplace_abn/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/lib/python3.5/site-packages/torch/lib/include -isystem /home/lib/python3.5/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/lib/python3.5/site-packages/torch/lib/include/TH -isystem /home/lib/python3.5/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/include/python3.5m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/lib/python3.5/site-packages/torch/lib/include -isystem /home/lib/python3.5/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/lib/python3.5/site-packages/torch/lib/include/TH -isystem /home/lib/python3.5/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/include/python3.5m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(286): error: namespace "thrust::cuda" has no member "par"

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(290): error: namespace "thrust::cuda" has no member "par"

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(286): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, lambda [](const double &)->double, lambda [](const double &)->__nv_bool)
          detected during instantiation of "void leaky_relu_backward_impl(T *, T *, float, int64_t) [with T=double]"
(302): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(290): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, lambda [](const double &)->double, lambda [](const double &)->__nv_bool)
          detected during instantiation of "void leaky_relu_backward_impl(T *, T *, float, int64_t) [with T=double]"
(302): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(286): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, lambda [](const float &)->float, lambda [](const float &)->__nv_bool)
          detected during instantiation of "void leaky_relu_backward_impl(T *, T *, float, int64_t) [with T=float]"
(302): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(290): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, lambda [](const float &)->float, lambda [](const float &)->__nv_bool)
          detected during instantiation of "void leaky_relu_backward_impl(T *, T *, float, int64_t) [with T=float]"
(302): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(314): error: namespace "thrust::cuda" has no member "par"

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(318): error: namespace "thrust::cuda" has no member "par"

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(314): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, lambda [](const double &, const double &)->double, lambda [](const double &)->__nv_bool)
          detected during instantiation of "void elu_backward_impl(T *, T *, int64_t) [with T=double]"
(330): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(318): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<double>, thrust::device_ptr<double>, thrust::device_ptr<double>, lambda [](const double &)->double, lambda [](const double &)->__nv_bool)
          detected during instantiation of "void elu_backward_impl(T *, T *, int64_t) [with T=double]"
(330): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(314): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, lambda [](const float &, const float &)->double, lambda [](const float &)->__nv_bool)
          detected during instantiation of "void elu_backward_impl(T *, T *, int64_t) [with T=float]"
(330): here

/home/developer/inplace_abn/modules/src/inplace_abn_cuda.cu(318): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, lambda [](const float &)->float, lambda [](const float &)->__nv_bool)
          detected during instantiation of "void elu_backward_impl(T *, T *, int64_t) [with T=float]"
(330): here

12 errors detected in the compilation of "/tmp/tmpxft_00006227_00000000-7_inplace_abn_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 14, in <module>
    import models
  File "/home/developer/inplace_abn/models/__init__.py", line 1, in <module>
    from .resnext import *
  File "/home/developer/inplace_abn/models/resnext.py", line 7, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "/home/developer/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/developer/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/developer/inplace_abn/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 964, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'inplace_abn'
```

I'm using CUDA 8.0., cuDNN 6.0.21, Ubuntu 16.04, python 3.5, pytorch 1.0 installed using pip. 
What might be the issue here? The file par.h (which seems to define par) is in my cuda folder so I'm not sure why it isn't getting picked up.

Thanks!

**Comment by PkuRainBow** [comment]
I also meet the similar problem as below,

![image](https://user-images.githubusercontent.com/4639578/51658013-920dee80-1fe1-11e9-90af-77c300b9785d.png)

**Comment by rotabulo** [comment]
@b-hahn do you get the same error with CUDA 9.2?

**Comment by b-hahn** [comment]
Unfortunately I'm constrained to using CUDA 8.0 so I can't tell you - are you aware of any features from CUDA 9.2 that are required? Would building pytorch from source solve any of these potential issues?
Thanks!

**Comment by b-hahn** [comment]
I can confirm that CUDA 9.2 solves the issue.

**Comment by sonack** [comment]
@b-hahn  How did you use the CUDA9.2 , I saw there is only 9.0 in pytorch website, and when I use it the problem remains.

**Comment by sonack** [comment]
> @b-hahn How did you use the CUDA9.2 , I saw there is only 9.0 in pytorch website, and when I use it the problem remains.

I got it! Indeed it is the cuda 8.0 wrong, but things a little different. I have several versions' CUDA installed, and the default `/usr/local/cuda` symbolic link to the `/usr/local/cuda-8.0`, which I don't have privilege to change it . Finally, I change the CUDA_HOME environment variable to `/usr/local/cuda-10.0`, and everything seems good.
