### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by alexalex1234** [mapillary/inplace_abn#9]
Hi, I have this error when I compile this repo
So, how can i fix it
Thanks

```
generating /tmp/tmpzzzetqi5/__ext.c
setting the current directory to '/tmp/tmpzzzetqi5'
running build_ext
building '__ext' extension
creating home
creating home/wang
creating home/wang/inplace_abn
creating home/wang/inplace_abn/modules
/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:154:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
#!/bin/bash
   for (int i = 0; i < 4; ++i) {
   ^
/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
#!/bin/bash
/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:172:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:190:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
#!/bin/bash
   ^
Traceback (most recent call last):
  File "/home/wang/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/wang/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/wang/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/wang/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wang/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/wang/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wang/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/wang/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/wang/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wang/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/wang/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/wang/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 24, in <module>
    ffi.build()
  File "/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 185, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1515, in recompile
    compiler_verbose, debug)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by ducksoup** [comment]
Hi @alexalex1234 , can you give me some additional information on your environment? From the error log it looks like some C++ code is being compiled using a C compiler, which shouldn't happen.

**Comment by alexalex1234** [comment]
I change the code in modules/build.py    
 extra_compile_args=["-std=c99"]
Then I can compile this repo.

Furthermore, what should I do the see the environment of my server.
I compile the Pytorch just like what their official repo said. 

I use Cuda9.0 and cudnn 6

Thanks

**Comment by ducksoup** [comment]
@alexalex1234 Is the code compiling and working correctly now that you added that flag?

**Comment by alexalex1234** [comment]
I haven't tried to train some model. But I change the flag, the repo can be compiled.
Maybe the version of gcc cause  the error.
My another sever's gcc version is 5.4 and can compile this repo correctly without any changes.

Thanks!

**Comment by ducksoup** [comment]
Yes, the bug could be related to the gcc version. I'll check whether adding that flag causes issues with other versions of gcc, otherwise I'll consider adding it as default.

Thank you for your report!
