### ISSUE TITLE
FileExistsError

### ISSUE THREAD

**Issue by lzrobots** [mapillary/inplace_abn#97]
```
Traceback (most recent call last):
  File "tool/train.py", line 22, in <module>
...
...
  File "/data/engs-tvg-lz/engs1870/projects/Seg/Semantic_Seg/model/net_block.py", line 3, in <module>
    from libs import InPlaceABNSync
  File "/data/engs-tvg-lz/engs1870/projects/Seg/Semantic_Seg/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/data/engs-tvg-lz/engs1870/projects/Seg/Semantic_Seg/libs/bn.py", line 10, in <module>
    from .functions import *
  File "/data/engs-tvg-lz/engs1870/projects/Seg/Semantic_Seg/libs/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/data/engs-tvg-lz/engs1870/anaconda3/envs/pytorch1.0_python3.7_cuda9.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 642, in load
    build_directory or _get_build_directory(name, verbose),
  File "/data/engs-tvg-lz/engs1870/anaconda3/envs/pytorch1.0_python3.7_cuda9.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 931, in _get_build_directory
    os.makedirs(build_directory)
  File "/data/engs-tvg-lz/engs1870/anaconda3/envs/pytorch1.0_python3.7_cuda9.2/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/torch_extensions/inplace_abn'
```

Hi above is the error I got everytime I run the training command line.
But it went well if I run the same training command line again.
I use DistributedDataParallel in training.
Did you have this problem before?

**Comment by rotabulo** [comment]
@lzrobots this happens to me as well sometimes and disappears by just restarting or by deleting `/tmp/torch_extensions`, but it is apparently not related to our code, because I had this also with other compiled modules.

**Comment by lzrobots** [comment]
I see but this is really annoying when queuing in the server.

**Comment by rotabulo** [comment]
@lzrobots this seems to be related to https://github.com/pytorch/pytorch/pull/6684 .
A possible workaround could be the following. Assume your script is `train.py` that you run on multiple gpus with `torch.distributed.launch`. You could first run `python train.py` to e.g. show the command line help and then run the script with all arguments. In this way the first run of the script (on a single process) will trigger the JIT compilation with no conflict, so that once you launch the script on multiple processes it finds the compiled scripts already cached.

**Comment by lzrobots** [comment]
```
...
...
File "/home/lz/Workspace/Seg/Semantic_Seg/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/lz/Workspace/Seg/Semantic_Seg/libs/bn.py", line 10, in <module>
    from .functions import *
  File "/home/lz/Workspace/Seg/Semantic_Seg/libs/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 968, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/lz/anaconda3/envs/pytorch1.0_python3.7/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
```

Got this cuda error but my CUDA is fine by testing on the NVIDIA_CUDA-9.2_Samples,
Don't know if it is caused by deleting `/tmp/torch_extensions`?

**Comment by rotabulo** [comment]
@lzrobots I don't think it's related. It is more likely that the libcudart library is not found. you could search its position and add `LD_LIBRARY_PATH=<folder to library> <your script>`

**Comment by lzrobots** [comment]
Thanks. the cuda problem solved.
For the FileExistsError, your suggestion works so far.
I first run `python -m torch.distributed.launch --nproc_per_node=$NGPUS train.py` without defining `config` and then run the same command line with full config definition.

I will close the issue to confirm if I don't get the error in the next couple of runs. Thanks.

**Comment by rotabulo** [comment]
@lzrobots you should better launch `python train.py` because otherwise you trigger again a parallel compilation.
